services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: folha-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - folha-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: folha-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - folha-network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: folha-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - folha-network

networks:
  folha-network:
    driver: bridge

volumes:
  pgdata:
